// <auto-generated />
using System;
using EFCorePerformance.Cmd.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCorePerformance.Cmd.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210105201931_firstindex")]
    partial class firstindex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportCommentWithBasicIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportCommentsWithBasicIndex");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportCommentWithBetterIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportCommentsWithBetterIndex");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportConfigWithBasicIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeryUsefulInformation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReportConfigsWithBasicIndexes");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportConfigWithBetterIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeryUsefulInformation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReportConfigsWithBetterIndexes");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportWithBasicIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ConfigId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.ToTable("ReportsWithBasicIndex");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportWithBetterIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ConfigId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.HasIndex("Name")
                        .HasFilter("[IsArchived] = 0")
                        .IncludeProperties(new[] { "Id", "Status" });

                    b.ToTable("ReportsWithBetterIndex");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportCommentWithBasicIndex", b =>
                {
                    b.HasOne("EFCorePerformance.Cmd.Model.ReportWithBasicIndex", "Report")
                        .WithMany("Comments")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportCommentWithBetterIndex", b =>
                {
                    b.HasOne("EFCorePerformance.Cmd.Model.ReportWithBetterIndex", "Report")
                        .WithMany("Comments")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportWithBasicIndex", b =>
                {
                    b.HasOne("EFCorePerformance.Cmd.Model.ReportConfigWithBasicIndex", "Config")
                        .WithMany("Reports")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportWithBetterIndex", b =>
                {
                    b.HasOne("EFCorePerformance.Cmd.Model.ReportConfigWithBetterIndex", "Config")
                        .WithMany("Reports")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportConfigWithBasicIndex", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportConfigWithBetterIndex", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportWithBasicIndex", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.ReportWithBetterIndex", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
