// <auto-generated />
using System;
using EFCorePerformance.Cmd.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCorePerformance.Cmd.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportCommentWithBasicIndex", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportCommentsWithBasicIndex");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportCommentWithBetterIndex", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportCommentsWithBetterIndex");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportConfigWithBasicIndex", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeryUsefulInformation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfigId");

                    b.ToTable("ReportConfigsWithBasicIndexes");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportConfigWithBetterIndex", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeryUsefulInformation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfigId");

                    b.ToTable("ReportConfigsWithBetterIndexes");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportWithBasicIndex", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ConfigId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ReportId");

                    b.HasIndex("ConfigId");

                    b.ToTable("ReportsWithBasicIndex");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportWithBetterIndex", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ConfigId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ReportId");

                    b.HasIndex("ConfigId");

                    b.HasIndex("Name")
                        .HasFilter("[IsArchived] = 0")
                        .IncludeProperties(new[] { "ReportId", "Status" });

                    b.ToTable("ReportsWithBetterIndex");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportCommentWithBasicIndex", b =>
                {
                    b.HasOne("EFCorePerformance.Cmd.Model.EF.ReportWithBasicIndex", "Report")
                        .WithMany("Comments")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportCommentWithBetterIndex", b =>
                {
                    b.HasOne("EFCorePerformance.Cmd.Model.EF.ReportWithBetterIndex", "Report")
                        .WithMany("Comments")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportWithBasicIndex", b =>
                {
                    b.HasOne("EFCorePerformance.Cmd.Model.EF.ReportConfigWithBasicIndex", "Config")
                        .WithMany("Reports")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportWithBetterIndex", b =>
                {
                    b.HasOne("EFCorePerformance.Cmd.Model.EF.ReportConfigWithBetterIndex", "Config")
                        .WithMany("Reports")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportConfigWithBasicIndex", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportConfigWithBetterIndex", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportWithBasicIndex", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("EFCorePerformance.Cmd.Model.EF.ReportWithBetterIndex", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
